[package]
name = "leafs-odyssey-manipulator"
version = "0.1.0"
edition = "2021"
default-run = "leafs-odyssey-manipulator"

[dependencies]
leafs-odyssey-data = { path = "../leafs-odyssey-data/" }
binrw = "0.14.1"
